### ISSUE TITLE
Error first deploy

### ISSUE THREAD

**Issue by rpsimao** [DALTCORE/laravel-deploy-helper#4] opened 2017-07-12 10:33 UTC
Hi

I'm trying to deploy, and get the following error:

```
[production] Trying to login into remote SSH
[production] Reading config file from remote server
[production] ldh.json does not exists.

 Do you want to initialize LDH here? (yes/no) [no]:
 > yes

 [ErrorException]                                     
 ksort() expects parameter 1 to be array, null given
``` 

In the remote server all the files are created but the file _ldh.json_ is empty.
In the question "Do you want...." I've tried both yes/no

Any help would be appreciated.
Thanks

**Comment by iJos** [comment] 2017-07-12 10:46
I am having the same problem, I think the problem is with the Deployer::freshInit method (The file is created, but it is filled later in the code). And when it needs to be filled, the .lock file already exist, so the execution is stopped...

**Comment by RamonSmit** [comment] 2017-07-12 11:08
Hi! 

I shall take a look into this one, It's quite weird. 
Give me a moment to reproduce this problem 

Edit 1:
Found the bug! Thanks for reporting.

**Comment by RamonSmit** [comment] 2017-07-12 11:20
Fixed! Added it to tag 1.0.7.

Thanks for letting me know! This one just really slipped trough

**Comment by rpsimao** [comment] 2017-07-12 11:22
You're most welcome.
Thanks

**Comment by RamonSmit** [comment] 2017-07-12 11:25
Let me know if you run into other trouble ;-)

**Comment by rpsimao** [comment] 2017-07-12 13:57
I run into another error:

```
..........
[root@192.168.1.230] (production) The compiled services file has been removed.
[production] Linking new release to /current directory and removing temp

 [ErrorException]              
 Undefined variable: toRemove  
```

Nevertheless the app was deployed.

One question:  the .env file is not copied to the deploy app, we have to create one?

Thanks

**Comment by RamonSmit** [comment] 2017-07-12 14:00
On the first deploy you have to manually create your .env (because it needs to be filled with your personal information) and the next following releases it will be copied over to the latest deployment 

On the ```[ErrorException]              
 Undefined variable: toRemove```  part, I will take a look on that one too. Give me a moment ;-)

**Comment by rpsimao** [comment] 2017-07-12 14:53
Also with that error the _.ldh-lockfile_ is not deleted, and cannot deploy another version.
Have to remove it manually

Also when deploy a new version:

```
[production] Trying to login into remote SSH
[production] Reading config file from remote server
[production] Found config. Checking directories.
**[production] Config file is empty... Something is wrong.**
```

The json config file is still empty, but it deploys the new version, and return again:

```
 [ErrorException]              
 Undefined variable: toRemove 
```

**Comment by RamonSmit** [comment] 2017-07-12 14:54
What Laravel version are you using if i may ask?

**Comment by rpsimao** [comment] 2017-07-12 14:56
5.4.28 - PHP 7.1.5

**Comment by RamonSmit** [comment] 2017-07-12 15:01
Hmm, I've updated LDH to 1.0.9, remove your `.ldh-lockfile` 
and 
The `Undefined variable: toRemove` should be fixed by now ;-)

**Comment by rpsimao** [comment] 2017-07-12 15:12
Ok the `Undefined variable: toRemove` error is fixed, still getting:
`[production] Config file is empty... Something is wrong.` error

App is deployed.

**Comment by rpsimao** [comment] 2017-07-12 15:19
So I erased everything from the production server and start over.
Made 2 deployments, **no errors**! :)

I think you can close this issue.
If I run into more troubles, I let you know.

**Comment by RamonSmit** [comment] 2017-07-12 15:28
Great! Good to know. I guess I have to write some tests for the future. 

Thanks for helping with the package, hope you like it :+1:

Cheers, 
Ramon

**Closed as completed by RamonSmit** 2017-07-12 15:28 UTC
Labels: bug
